### PR TITLE
Don't copy plist unless it doesn't exist

### PR DESCRIPTION
**Pull request by malston**

### CODE REVIEW

**Comment by hiremaga** [comment]
Thanks for the PR @malston

This change seems reasonable. Can this be expressed as a [not_if](https://docs.getchef.com/resource_common.html#not-if-examples) instead?

**Comment by malston** [comment]
Thanks for the fast turn-around.

**Comment by hiremaga** [comment]
Thank you!

I think destination can safely be pulled out of the ruby_block block, so it
can be reused in the not_if.

Less likely to go out of sync this way.

**Comment by aramprice** [comment]
I just saw this issue as well:

```
    ================================================================================
    Error executing action `run` on resource 'ruby_block[copy mysql plist to ~/Library/LaunchAgents]'
    ================================================================================

    RuntimeError
    ------------
    Couldn't find the plist

    Cookbook Trace:
    ---------------
    /cookbooks/sprout-mysql/recipes/install.rb:27:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /cookbooks/sprout-mysql/recipes/install.rb

     22: ruby_block 'copy mysql plist to ~/Library/LaunchAgents' do
     23:   block do
     24:     active_mysql = Pathname.new('/usr/local/bin/mysql').realpath
     25:     plist_location = (active_mysql + '../../' + 'homebrew.mxcl.mysql.plist').to_s
     26:     destination = "#{node['sprout']['home']}/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
     27:     system("cp #{plist_location} #{destination} && chown #{node['sprout']['user']} #{destination}") || fail("Couldn't find the plist")
     28:   end
     29: end
     30:

    Compiled Resource:
    ------------------
    # Declared in /cookbooks/sprout-mysql/recipes/install.rb:22:in `from_file'

    ruby_block("copy mysql plist to ~/Library/LaunchAgents") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "copy mysql plist to ~/Library/LaunchAgents"
      declared_type :ruby_block
      cookbook_name :"sprout-mysql"
      recipe_name "install"
      block #<Proc:0x007f9e8b697d10@/cookbooks/sprout-mysql/recipes/install.rb:23>
    end
```

Probably a change in `brew` which removed this file - I only saw the error after running `brew update`

**Pull request closed without merging**
